name = "trains"
compatibility_date = "2025-08-21"

main = "./dist/_worker.js/index.js"

[assets]
binding = "ASSETS"
directory = "./dist"

[[routes]]
custom_domain = true
pattern = "trains.willow.sh"

[observability]
enabled = true

[[kv_namespaces]]
binding = "CACHE"
id = "75f60ecca7d94dcdb6458dbbcf6b0b2b"
